import 'package:flutter/material.dart';
import 'package:flutter/foundation.dart';
import 'package:shared_preferences/shared_preferences.dart';

const _kLocaleStorageKey = '__locale_key__';

class FFLocalizations {
  FFLocalizations(this.locale);

  final Locale locale;

  static FFLocalizations of(BuildContext context) =>
      Localizations.of<FFLocalizations>(context, FFLocalizations)!;

  static List<String> languages() => ['es', 'en', 'de', 'ar'];

  static late SharedPreferences _prefs;
  static Future initialize() async =>
      _prefs = await SharedPreferences.getInstance();
  static Future storeLocale(String locale) =>
      _prefs.setString(_kLocaleStorageKey, locale);
  static Locale? getStoredLocale() {
    final locale = _prefs.getString(_kLocaleStorageKey);
    return locale != null && locale.isNotEmpty ? createLocale(locale) : null;
  }

  String get languageCode => locale.toString();
  String? get languageShortCode =>
      _languagesWithShortCode.contains(locale.toString())
          ? '${locale.toString()}_short'
          : null;
  int get languageIndex => languages().contains(languageCode)
      ? languages().indexOf(languageCode)
      : 0;

  String getText(String key) =>
      (kTranslationsMap[key] ?? {})[locale.toString()] ?? '';

  String getVariableText({
    String? esText = '',
    String? enText = '',
    String? deText = '',
    String? arText = '',
  }) =>
      [esText, enText, deText, arText][languageIndex] ?? '';

  static const Set<String> _languagesWithShortCode = {
    'ar',
    'az',
    'ca',
    'cs',
    'da',
    'de',
    'dv',
    'en',
    'es',
    'et',
    'fi',
    'fr',
    'gr',
    'he',
    'hi',
    'hu',
    'it',
    'km',
    'ku',
    'mn',
    'ms',
    'no',
    'pt',
    'ro',
    'ru',
    'rw',
    'sv',
    'th',
    'uk',
    'vi',
  };
}

class FFLocalizationsDelegate extends LocalizationsDelegate<FFLocalizations> {
  const FFLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) {
    final language = locale.toString();
    return FFLocalizations.languages().contains(
      language.endsWith('_')
          ? language.substring(0, language.length - 1)
          : language,
    );
  }

  @override
  Future<FFLocalizations> load(Locale locale) =>
      SynchronousFuture<FFLocalizations>(FFLocalizations(locale));

  @override
  bool shouldReload(FFLocalizationsDelegate old) => false;
}

Locale createLocale(String language) => language.contains('_')
    ? Locale.fromSubtags(
        languageCode: language.split('_').first,
        scriptCode: language.split('_').last,
      )
    : Locale(language);

final kTranslationsMap = <Map<String, Map<String, String>>>[
  // loginPage
  {
    'o07j3mgv': {
      'es': 'Welcome back',
      'ar': '',
      'de': '',
      'en': '',
    },
    'fzxvw3mu': {
      'es': 'Login to access your account below.',
      'ar': '',
      'de': '',
      'en': '',
    },
    'a9j78va9': {
      'es': 'Email Address',
      'ar': '',
      'de': '',
      'en': '',
    },
    'i7f18cve': {
      'es': 'Enter your email...',
      'ar': '',
      'de': '',
      'en': '',
    },
    'wztjmbn8': {
      'es': 'Password',
      'ar': '',
      'de': '',
      'en': '',
    },
    'lw1jpm1f': {
      'es': 'Enter your password...',
      'ar': '',
      'de': '',
      'en': '',
    },
    'm2xyjvuf': {
      'es': 'Forgot Password?',
      'ar': '',
      'de': '',
      'en': '',
    },
    'qbmoi1av': {
      'es': 'Login',
      'ar': '',
      'de': '',
      'en': '',
    },
    'cjqb8ial': {
      'es': 'Don\'t have an account?',
      'ar': '',
      'de': '',
      'en': '',
    },
    'a0iimirx': {
      'es': 'Create',
      'ar': '',
      'de': '',
      'en': '',
    },
    '2bb3vct7': {
      'es': 'Home',
      'ar': '',
      'de': '',
      'en': '',
    },
  },
  // registerAccount
  {
    'gpokmd81': {
      'es': 'Get Started',
      'ar': '',
      'de': '',
      'en': '',
    },
    'oitrrwgg': {
      'es': 'Create your account below.',
      'ar': '',
      'de': '',
      'en': '',
    },
    'gcwdqm4g': {
      'es': 'Email Address',
      'ar': '',
      'de': '',
      'en': '',
    },
    'iam0xgwx': {
      'es': 'Enter your email...',
      'ar': '',
      'de': '',
      'en': '',
    },
    'bqv15dcf': {
      'es': 'Password',
      'ar': '',
      'de': '',
      'en': '',
    },
    'joih97mn': {
      'es': 'Enter your password...',
      'ar': '',
      'de': '',
      'en': '',
    },
    'rzpiwq9p': {
      'es': 'Confirm Password',
      'ar': '',
      'de': '',
      'en': '',
    },
    'eyfkffka': {
      'es': 'Enter your password...',
      'ar': '',
      'de': '',
      'en': '',
    },
    '5kmjfwsk': {
      'es': 'Create Account',
      'ar': '',
      'de': '',
      'en': '',
    },
    '3twynvfz': {
      'es': 'Login',
      'ar': '',
      'de': '',
      'en': '',
    },
    '9ssznj0g': {
      'es': 'Already have an account?',
      'ar': '',
      'de': '',
      'en': '',
    },
    'momge5oj': {
      'es': 'Home',
      'ar': '',
      'de': '',
      'en': '',
    },
  },
  // completeProfile
  {
    'yhcaf7r2': {
      'es': 'Complete Profile',
      'ar': '',
      'de': '',
      'en': '',
    },
    'r6npjsue': {
      'es': 'Upload a photo for us to easily identify you.',
      'ar': '',
      'de': '',
      'en': '',
    },
    'sdptn7dd': {
      'es': 'Your Name',
      'ar': '',
      'de': '',
      'en': '',
    },
    'n636qnrx': {
      'es': 'Your Age',
      'ar': '',
      'de': '',
      'en': '',
    },
    's7yvjzbs': {
      'es': 'i.e. 34',
      'ar': '',
      'de': '',
      'en': '',
    },
    '72ii0waq': {
      'es': 'Your Title',
      'ar': '',
      'de': '',
      'en': '',
    },
    'pf8glhkg': {
      'es': 'What is your position?',
      'ar': '',
      'de': '',
      'en': '',
    },
    'hbhd3bdt': {
      'es': 'Complete Profile',
      'ar': '',
      'de': '',
      'en': '',
    },
    '1eac148w': {
      'es': 'Field is required',
      'ar': '',
      'de': '',
      'en': '',
    },
    'ew7dbn3s': {
      'es': 'Field is required',
      'ar': '',
      'de': '',
      'en': '',
    },
    'jhhlgzk5': {
      'es': 'Field is required',
      'ar': '',
      'de': '',
      'en': '',
    },
    '4k3jnl38': {
      'es': 'Home',
      'ar': '',
      'de': '',
      'en': '',
    },
  },
  // forgotPassword
  {
    'g416xg9f': {
      'es': 'Forgot Password',
      'ar': '',
      'de': '',
      'en': '',
    },
    'xaiad71o': {
      'es':
          'Enter the email associated with your account and we will send you a verification code.',
      'ar': '',
      'de': '',
      'en': '',
    },
    'u4nuk910': {
      'es': 'Email Address',
      'ar': '',
      'de': '',
      'en': '',
    },
    '37kotxi0': {
      'es': 'Enter your email...',
      'ar': '',
      'de': '',
      'en': '',
    },
    'hiwpaze1': {
      'es': 'Send Reset Link',
      'ar': '',
      'de': '',
      'en': '',
    },
    '598b8d3m': {
      'es': 'Home',
      'ar': '',
      'de': '',
      'en': '',
    },
  },
  // MY_Card
  {
    '6t7n9ugd': {
      'es': 'Balance',
      'ar': '',
      'de': '',
      'en': '',
    },
    'eeky0wf2': {
      'es': '\$7,630',
      'ar': '',
      'de': '',
      'en': '',
    },
    'dntk53bl': {
      'es': 'Wallet',
      'ar': '',
      'de': '',
      'en': '',
    },
    'lr97k2rc': {
      'es': '**** 0149',
      'ar': '',
      'de': '',
      'en': '',
    },
    'l9racj60': {
      'es': '05/25',
      'ar': '',
      'de': '',
      'en': '',
    },
    'yet7zk5d': {
      'es': 'Quick Service',
      'ar': '',
      'de': '',
      'en': '',
    },
    '8bnd6lco': {
      'es': 'Transfer',
      'ar': '',
      'de': '',
      'en': '',
    },
    'roobc02h': {
      'es': 'Block Card',
      'ar': '',
      'de': '',
      'en': '',
    },
    '27pb7ji4': {
      'es': 'Transaction',
      'ar': '',
      'de': '',
      'en': '',
    },
    'ymfmz1ax': {
      'es': 'Dribbble LTD.',
      'ar': '',
      'de': '',
      'en': '',
    },
    'o08jnodl': {
      'es': 'Paid on: May, 4th 2023',
      'ar': '',
      'de': '',
      'en': '',
    },
    'sriclhoq': {
      'es': '\$500.00',
      'ar': '',
      'de': '',
      'en': '',
    },
    'cgsqlide': {
      'es': 'Overdue',
      'ar': '',
      'de': '',
      'en': '',
    },
    'mgleghvd': {
      'es': 'FlutterFlow',
      'ar': '',
      'de': '',
      'en': '',
    },
    '1igtvnk2': {
      'es': 'Paid on: May, 4th 2023',
      'ar': '',
      'de': '',
      'en': '',
    },
    'qvrdky9h': {
      'es': '\$500.00',
      'ar': '',
      'de': '',
      'en': '',
    },
    '1915bsre': {
      'es': 'Overdue',
      'ar': '',
      'de': '',
      'en': '',
    },
    '818kwp79': {
      'es': 'ScreenStudio App',
      'ar': '',
      'de': '',
      'en': '',
    },
    '4hkh9400': {
      'es': 'Paid on: May, 4th 2023',
      'ar': '',
      'de': '',
      'en': '',
    },
    'o2bnhrqf': {
      'es': '\$24.99',
      'ar': '',
      'de': '',
      'en': '',
    },
    '56xp8lap': {
      'es': 'Paid',
      'ar': '',
      'de': '',
      'en': '',
    },
    '6j0nslbr': {
      'es': 'Slack Ltd',
      'ar': '',
      'de': '',
      'en': '',
    },
    'hwnkex2v': {
      'es': 'Paid on: May, 4th 2023',
      'ar': '',
      'de': '',
      'en': '',
    },
    'o0dd4h7m': {
      'es': '\$24.99',
      'ar': '',
      'de': '',
      'en': '',
    },
    '03ibk0hz': {
      'es': 'Paid',
      'ar': '',
      'de': '',
      'en': '',
    },
    '7gucduid': {
      'es': 'Wallet',
      'ar': '',
      'de': '',
      'en': '',
    },
    'm8rhanhc': {
      'es': '•',
      'ar': '',
      'de': '',
      'en': '',
    },
  },
  // MY_profilePage
  {
    'i16gr6pz': {
      'es': '[User Name Here]',
      'ar': '',
      'de': '',
      'en': '',
    },
    'eixjjzil': {
      'es': 'User.name@domainname.com',
      'ar': '',
      'de': '',
      'en': '',
    },
    'f1bvbey3': {
      'es': 'My Account',
      'ar': '',
      'de': '',
      'en': '',
    },
    'i61y9ibx': {
      'es': 'Edit Profile',
      'ar': '',
      'de': '',
      'en': '',
    },
    '03k0vw86': {
      'es': 'Change Password',
      'ar': '',
      'de': '',
      'en': '',
    },
    '6w6wv95p': {
      'es': 'Notification Settings',
      'ar': '',
      'de': '',
      'en': '',
    },
    '9aogde79': {
      'es': 'Tutorial',
      'ar': '',
      'de': '',
      'en': '',
    },
    'eojlfs66': {
      'es': 'Privacy Policy',
      'ar': '',
      'de': '',
      'en': '',
    },
    '2ll42t1u': {
      'es': 'Dark Mode',
      'ar': '',
      'de': '',
      'en': '',
    },
    '8d386226': {
      'es': 'Light Mode',
      'ar': '',
      'de': '',
      'en': '',
    },
    '8srr2k0j': {
      'es': '•',
      'ar': '',
      'de': '',
      'en': '',
    },
  },
  // transferComplete
  {
    'xf8d4sm8': {
      'es': 'Transfer Complete',
      'ar': '',
      'de': '',
      'en': '',
    },
    'iq9jjji8': {
      'es':
          'Great work, you successfully transferred funds. It may take a few days for the funds to leave your account.',
      'ar': '',
      'de': '',
      'en': '',
    },
    'wrbg19ed': {
      'es': 'Okay',
      'ar': '',
      'de': '',
      'en': '',
    },
    'ndkybnrt': {
      'es': 'Home',
      'ar': '',
      'de': '',
      'en': '',
    },
  },
  // transferFunds
  {
    'pe3o18oh': {
      'es': 'Transfer Funds',
      'ar': '',
      'de': '',
      'en': '',
    },
    'kyzwrfh4': {
      'es': 'Balance',
      'ar': '',
      'de': '',
      'en': '',
    },
    'zq4ozx20': {
      'es': '\$7,630',
      'ar': '',
      'de': '',
      'en': '',
    },
    'qukh7yo1': {
      'es': '**** 0149',
      'ar': '',
      'de': '',
      'en': '',
    },
    'n87hkr7d': {
      'es': '05/25',
      'ar': '',
      'de': '',
      'en': '',
    },
    '3ct4fj7p': {
      'es': 'Change Account',
      'ar': '',
      'de': '',
      'en': '',
    },
    'w4smsh2i': {
      'es': 'Internal Transfer',
      'ar': '',
      'de': '',
      'en': '',
    },
    '6uxty3hy': {
      'es': 'External Transfer',
      'ar': '',
      'de': '',
      'en': '',
    },
    'p4ngma0d': {
      'es': 'ACH Payment',
      'ar': '',
      'de': '',
      'en': '',
    },
    'uxo87fjc': {
      'es': 'Transfer Type',
      'ar': '',
      'de': '',
      'en': '',
    },
    'fddma8xl': {
      'es': 'Select Account',
      'ar': '',
      'de': '',
      'en': '',
    },
    '23l6kqgm': {
      'es': 'Account ****2010',
      'ar': '',
      'de': '',
      'en': '',
    },
    '3hwdfadf': {
      'es': 'Account ****2011',
      'ar': '',
      'de': '',
      'en': '',
    },
    'xvj00xg1': {
      'es': 'Account ****2012',
      'ar': '',
      'de': '',
      'en': '',
    },
    'ok5xluvk': {
      'es': 'Choose an Account',
      'ar': '',
      'de': '',
      'en': '',
    },
    'ynie0pc5': {
      'es': '\$ Amount',
      'ar': '',
      'de': '',
      'en': '',
    },
    'wngoi0v4': {
      'es': 'Your new account balance is:',
      'ar': '',
      'de': '',
      'en': '',
    },
    'g6bfec2g': {
      'es': '\$7,630',
      'ar': '',
      'de': '',
      'en': '',
    },
    'xaw2jdst': {
      'es': 'Send Transfer',
      'ar': '',
      'de': '',
      'en': '',
    },
    'xku4zxbe': {
      'es': 'Tap above to complete transfer',
      'ar': '',
      'de': '',
      'en': '',
    },
    'imaejg7x': {
      'es': 'Home',
      'ar': '',
      'de': '',
      'en': '',
    },
  },
  // editProfile
  {
    '4rzqov3y': {
      'es': 'Edit Profile',
      'ar': '',
      'de': '',
      'en': '',
    },
    'zoxan2gi': {
      'es': 'Change Photo',
      'ar': '',
      'de': '',
      'en': '',
    },
    '3p9y21e2': {
      'es': 'Your Name',
      'ar': '',
      'de': '',
      'en': '',
    },
    'dw9gmjdc': {
      'es': 'Please enter a valid number...',
      'ar': '',
      'de': '',
      'en': '',
    },
    'z4fstn5l': {
      'es': 'Email Address',
      'ar': '',
      'de': '',
      'en': '',
    },
    'jozgvwyg': {
      'es': 'Your email',
      'ar': '',
      'de': '',
      'en': '',
    },
    '8h1cjk5a': {
      'es': 'Your Age',
      'ar': '',
      'de': '',
      'en': '',
    },
    '5v21r6gb': {
      'es': 'i.e. 34',
      'ar': '',
      'de': '',
      'en': '',
    },
    'zvymbfia': {
      'es': 'Your Title',
      'ar': '',
      'de': '',
      'en': '',
    },
    'i6edcl52': {
      'es': 'Save Changes',
      'ar': '',
      'de': '',
      'en': '',
    },
    '59naq8ur': {
      'es': 'Home',
      'ar': '',
      'de': '',
      'en': '',
    },
  },
  // changePassword
  {
    'l5iggwaz': {
      'es': 'Change Password',
      'ar': '',
      'de': '',
      'en': '',
    },
    '2b97u8y5': {
      'es':
          'Enter the email associated with your account and we will send you link to reset your password.',
      'ar': '',
      'de': '',
      'en': '',
    },
    'ajy1c3r9': {
      'es': 'Email Address',
      'ar': '',
      'de': '',
      'en': '',
    },
    'hsqfoxya': {
      'es': 'Enter your email...',
      'ar': '',
      'de': '',
      'en': '',
    },
    'if4pz6lm': {
      'es': 'Send Reset Link',
      'ar': '',
      'de': '',
      'en': '',
    },
    '5tvk9lv0': {
      'es': 'Home',
      'ar': '',
      'de': '',
      'en': '',
    },
  },
  // notificationsSettings
  {
    'sc4ff4ce': {
      'es': 'Notifications',
      'ar': '',
      'de': '',
      'en': '',
    },
    'r72zvrv5': {
      'es':
          'Choose what notifcations you want to recieve below and we will update the settings.',
      'ar': '',
      'de': '',
      'en': '',
    },
    'gjygkr0n': {
      'es': 'Push Notifications',
      'ar': '',
      'de': '',
      'en': '',
    },
    '3y3yhxbk': {
      'es':
          'Receive Push notifications from our application on a semi regular basis.',
      'ar': '',
      'de': '',
      'en': '',
    },
    '1ytebj35': {
      'es': 'Email Notifications',
      'ar': '',
      'de': '',
      'en': '',
    },
    '9lvh5nst': {
      'es':
          'Receive email notifications from our marketing team about new features.',
      'ar': '',
      'de': '',
      'en': '',
    },
    '69d2j74u': {
      'es': 'Location Services',
      'ar': '',
      'de': '',
      'en': '',
    },
    '3k8cuv0d': {
      'es':
          'Allow us to track your location, this helps keep track of spending and keeps you safe.',
      'ar': '',
      'de': '',
      'en': '',
    },
    'isgrgbfs': {
      'es': 'Save Changes',
      'ar': '',
      'de': '',
      'en': '',
    },
    'a96mlyeh': {
      'es': 'Home',
      'ar': '',
      'de': '',
      'en': '',
    },
  },
  // privacyPolicy
  {
    'alczfiiy': {
      'es': 'Privacy Policy',
      'ar': '',
      'de': '',
      'en': '',
    },
    'fvsfg5on': {
      'es': 'How we use your data',
      'ar': '',
      'de': '',
      'en': '',
    },
    'nbiyrnzl': {
      'es':
          'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Accumsan sit amet nulla facilisi morbi tempus. Non consectetur a erat nam. Donec ultrices tincidunt arcu non sodales. Velit sed ullamcorper morbi tincidunt. Molestie a iaculis at erat pellentesque adipiscing. Mauris nunc congue nisi vitae. Nisl tincidunt eget nullam non nisi. Faucibus nisl tincidunt eget nullam non nisi est. Leo duis ut diam quam nulla.\n\nEuismod lacinia at quis risus sed vulputate odio. Velit dignissim sodales ut eu sem integer vitae justo eget. Risus feugiat in ante metus. Leo vel orci porta non pulvinar neque laoreet suspendisse interdum. Suscipit tellus mauris a diam maecenas sed enim ut sem. Sem integer vitae justo eget magna fermentum iaculis eu. Lacinia at quis risus sed. Faucibus purus in massa tempor. Leo a diam sollicitudin tempor id eu. Nisi scelerisque eu ultrices vitae auctor. Vulputate dignissim suspendisse in est ante in. Enim neque volutpat ac tincidunt vitae semper quis. Ipsum dolor sit amet consectetur adipiscing elit.\n\nEt malesuada fames ac turpis egestas maecenas pharetra convallis. Sed sed risus pretium quam vulputate. Elit pellentesque habitant morbi tristique senectus et. Viverra maecenas accumsan lacus vel facilisis volutpat est. Sit amet mattis vulputate enim nulla. Nisi lacus sed viverra tellus in hac habitasse. Sit amet risus nullam eget felis eget nunc lobortis. Pretium lectus quam id leo in vitae. Adipiscing diam donec adipiscing tristique. Commodo sed egestas egestas fringilla. Ipsum dolor sit amet consectetur adipiscing. Ipsum dolor sit amet consectetur adipiscing elit pellentesque habitant morbi. Montes nascetur ridiculus mus mauris. Ut etiam sit amet nisl purus in. Arcu ac tortor dignissim convallis aenean et tortor at. Ornare suspendisse sed nisi lacus sed viverra.',
      'ar': '',
      'de': '',
      'en': '',
    },
    'oks4x95o': {
      'es': 'Home',
      'ar': '',
      'de': '',
      'en': '',
    },
  },
  // tutorial_PROFILE
  {
    '38wb3rix': {
      'es': 'Tutorial',
      'ar': '',
      'de': '',
      'en': '',
    },
    'o6prpb1q': {
      'es': 'Create Budgets',
      'ar': '',
      'de': '',
      'en': '',
    },
    '292pbdw7': {
      'es':
          'Create budgets that you can tie transactions too in order for easy tracking.',
      'ar': '',
      'de': '',
      'en': '',
    },
    'b10xvuf9': {
      'es': 'Keep Track of Spending',
      'ar': '',
      'de': '',
      'en': '',
    },
    't6k1smsm': {
      'es':
          'Easily add transactions and associate them with budgets that have been created.',
      'ar': '',
      'de': '',
      'en': '',
    },
    'u8xxj427': {
      'es': 'Budget Analysis',
      'ar': '',
      'de': '',
      'en': '',
    },
    'iqi0pkmb': {
      'es': 'Know where your budgets are and how they can be adjusted.',
      'ar': '',
      'de': '',
      'en': '',
    },
    'uydm0fnm': {
      'es': 'Home',
      'ar': '',
      'de': '',
      'en': '',
    },
  },
  // homePage_alt
  {
    'xdh0z8qh': {
      'es': 'Welcome,',
      'ar': '',
      'de': '',
      'en': '',
    },
    'v74pa882': {
      'es': 'Andrew',
      'ar': '',
      'de': '',
      'en': '',
    },
    'rzpg3cvh': {
      'es': 'Your latest updates are below.',
      'ar': '',
      'de': '',
      'en': '',
    },
    'flto6ti8': {
      'es': 'Total Balance',
      'ar': '',
      'de': '',
      'en': '',
    },
    'g07h0azf': {
      'es': '\$25,281',
      'ar': '',
      'de': '',
      'en': '',
    },
    'v9ghmn0y': {
      'es': 'Total Balance',
      'ar': '',
      'de': '',
      'en': '',
    },
    '7vf40ybo': {
      'es': '\$25,281',
      'ar': '',
      'de': '',
      'en': '',
    },
    'k4scs2cu': {
      'es': 'Total Balance',
      'ar': '',
      'de': '',
      'en': '',
    },
    'cvrbfozm': {
      'es': '\$25,281',
      'ar': '',
      'de': '',
      'en': '',
    },
    'a33ldz0h': {
      'es': 'Next Payroll',
      'ar': '',
      'de': '',
      'en': '',
    },
    '3dgzzz79': {
      'es': '\$25,281',
      'ar': '',
      'de': '',
      'en': '',
    },
    'hp28r17l': {
      'es': 'Debit Date',
      'ar': '',
      'de': '',
      'en': '',
    },
    'k04gl6sz': {
      'es': 'Aug 31, 2021',
      'ar': '',
      'de': '',
      'en': '',
    },
    'd5tcdo3w': {
      'es': '4 days left',
      'ar': '',
      'de': '',
      'en': '',
    },
    '8wofym4i': {
      'es': '1 New Alert',
      'ar': '',
      'de': '',
      'en': '',
    },
    'kaq4nzj6': {
      'es': 'Fraud Alert',
      'ar': '',
      'de': '',
      'en': '',
    },
    '7zcrtqx6': {
      'es':
          'We noticed a small charge that is out of character of this account, please review.',
      'ar': '',
      'de': '',
      'en': '',
    },
    '23yxoc9m': {
      'es': 'View Now',
      'ar': '',
      'de': '',
      'en': '',
    },
    'a86mwddx': {
      'es': 'Marketing Budget',
      'ar': '',
      'de': '',
      'en': '',
    },
    '6c2o39hz': {
      'es': '\$3,000',
      'ar': '',
      'de': '',
      'en': '',
    },
    '5subrra4': {
      'es': 'Total Spent',
      'ar': '',
      'de': '',
      'en': '',
    },
    '0wtm2m51': {
      'es': '\$2,502',
      'ar': '',
      'de': '',
      'en': '',
    },
    'bp9d56pc': {
      'es': '4 days left',
      'ar': '',
      'de': '',
      'en': '',
    },
    'b8oj0pck': {
      'es': 'Team Name',
      'ar': '',
      'de': '',
      'en': '',
    },
    '87ospwsq': {
      'es': '\$5,000',
      'ar': '',
      'de': '',
      'en': '',
    },
    'jzfejglt': {
      'es': 'Head of Design',
      'ar': '',
      'de': '',
      'en': '',
    },
    'zm0lhm2a': {
      'es': '[Time Stamp]',
      'ar': '',
      'de': '',
      'en': '',
    },
    '8hu2v2im': {
      'es': '•',
      'ar': '',
      'de': '',
      'en': '',
    },
  },
  // Alerts
  {
    'qpphkxhk': {
      'es': 'Below are a summary of your invoices.',
      'ar': '',
      'de': '',
      'en': '',
    },
    'bbhozegw': {
      'es': 'All',
      'ar': '',
      'de': '',
      'en': '',
    },
    '78862695': {
      'es': 'Today',
      'ar': '',
      'de': '',
      'en': '',
    },
    '5glur0sb': {
      'es': 'ScreenStudio App',
      'ar': '',
      'de': '',
      'en': '',
    },
    '6zrgy5ee': {
      'es': 'Paid on: May, 4th 2023',
      'ar': '',
      'de': '',
      'en': '',
    },
    '4fpjdh14': {
      'es': '\$24.99',
      'ar': '',
      'de': '',
      'en': '',
    },
    'tl0kkc1y': {
      'es': 'DUE',
      'ar': '',
      'de': '',
      'en': '',
    },
    'sxcmbcpl': {
      'es': 'Slack Ltd',
      'ar': '',
      'de': '',
      'en': '',
    },
    'membk7he': {
      'es': 'Paid on: May, 4th 2023',
      'ar': '',
      'de': '',
      'en': '',
    },
    'tw9vzm2z': {
      'es': '\$24.99',
      'ar': '',
      'de': '',
      'en': '',
    },
    'dd9y8p8p': {
      'es': 'DUE',
      'ar': '',
      'de': '',
      'en': '',
    },
    'lfoac4wc': {
      'es': 'Earlier Invoices',
      'ar': '',
      'de': '',
      'en': '',
    },
    'oayo3ibx': {
      'es': 'Dribbble LTD.',
      'ar': '',
      'de': '',
      'en': '',
    },
    'e8w9zk02': {
      'es': 'Paid on: May, 4th 2023',
      'ar': '',
      'de': '',
      'en': '',
    },
    'e9aj60e0': {
      'es': '\$500.00',
      'ar': '',
      'de': '',
      'en': '',
    },
    'k6rl2imr': {
      'es': 'Overdue',
      'ar': '',
      'de': '',
      'en': '',
    },
    'qy2wr3rz': {
      'es': 'FlutterFlow',
      'ar': '',
      'de': '',
      'en': '',
    },
    '8id4gtww': {
      'es': 'Paid on: May, 4th 2023',
      'ar': '',
      'de': '',
      'en': '',
    },
    'nls7la9q': {
      'es': '\$500.00',
      'ar': '',
      'de': '',
      'en': '',
    },
    'e1yi3u0h': {
      'es': 'Overdue',
      'ar': '',
      'de': '',
      'en': '',
    },
    't7uidd1y': {
      'es': 'ScreenStudio App',
      'ar': '',
      'de': '',
      'en': '',
    },
    'rhu6ii6p': {
      'es': 'Paid on: May, 4th 2023',
      'ar': '',
      'de': '',
      'en': '',
    },
    'opzrfsoj': {
      'es': '\$24.99',
      'ar': '',
      'de': '',
      'en': '',
    },
    'eqctpmwt': {
      'es': 'Paid',
      'ar': '',
      'de': '',
      'en': '',
    },
    'iktvsqab': {
      'es': 'Slack Ltd',
      'ar': '',
      'de': '',
      'en': '',
    },
    '4zrzvb5j': {
      'es': 'Paid on: May, 4th 2023',
      'ar': '',
      'de': '',
      'en': '',
    },
    '2m1drjvq': {
      'es': '\$24.99',
      'ar': '',
      'de': '',
      'en': '',
    },
    '2fyhlcvf': {
      'es': 'Paid',
      'ar': '',
      'de': '',
      'en': '',
    },
    '1fdi42ga': {
      'es': 'Open',
      'ar': '',
      'de': '',
      'en': '',
    },
    '1n01lg65': {
      'es': 'Today',
      'ar': '',
      'de': '',
      'en': '',
    },
    'nhb3maj5': {
      'es': 'ScreenStudio App',
      'ar': '',
      'de': '',
      'en': '',
    },
    'ligmv9ny': {
      'es': 'Paid on: May, 4th 2023',
      'ar': '',
      'de': '',
      'en': '',
    },
    'zjsrrl7l': {
      'es': '\$24.99',
      'ar': '',
      'de': '',
      'en': '',
    },
    'ee0d31sn': {
      'es': 'DUE',
      'ar': '',
      'de': '',
      'en': '',
    },
    'yazherss': {
      'es': 'Slack Ltd',
      'ar': '',
      'de': '',
      'en': '',
    },
    'fxx45pdm': {
      'es': 'Paid on: May, 4th 2023',
      'ar': '',
      'de': '',
      'en': '',
    },
    'usyuydjm': {
      'es': '\$24.99',
      'ar': '',
      'de': '',
      'en': '',
    },
    'jkbxny8a': {
      'es': 'DUE',
      'ar': '',
      'de': '',
      'en': '',
    },
    'dq97de3p': {
      'es': 'Earlier Invoices',
      'ar': '',
      'de': '',
      'en': '',
    },
    '0k43ysyf': {
      'es': 'Dribbble LTD.',
      'ar': '',
      'de': '',
      'en': '',
    },
    'osufh299': {
      'es': 'Paid on: May, 4th 2023',
      'ar': '',
      'de': '',
      'en': '',
    },
    'p2x4p7al': {
      'es': '\$500.00',
      'ar': '',
      'de': '',
      'en': '',
    },
    'k5271i5p': {
      'es': 'Overdue',
      'ar': '',
      'de': '',
      'en': '',
    },
    'ghv8jfi2': {
      'es': 'FlutterFlow',
      'ar': '',
      'de': '',
      'en': '',
    },
    '2u0xoar7': {
      'es': 'Paid on: May, 4th 2023',
      'ar': '',
      'de': '',
      'en': '',
    },
    'os0e90vd': {
      'es': '\$500.00',
      'ar': '',
      'de': '',
      'en': '',
    },
    '0x13josh': {
      'es': 'Overdue',
      'ar': '',
      'de': '',
      'en': '',
    },
    'y557tb4i': {
      'es': 'Paid',
      'ar': '',
      'de': '',
      'en': '',
    },
    'twso6h76': {
      'es': 'Earlier Invoices',
      'ar': '',
      'de': '',
      'en': '',
    },
    '3ivh9dzf': {
      'es': 'Dribbble LTD.',
      'ar': '',
      'de': '',
      'en': '',
    },
    'ge0zdbcu': {
      'es': 'Paid on: May, 4th 2023',
      'ar': '',
      'de': '',
      'en': '',
    },
    'bhlgtd2h': {
      'es': '\$500.00',
      'ar': '',
      'de': '',
      'en': '',
    },
    'bc7e2819': {
      'es': 'Paid',
      'ar': '',
      'de': '',
      'en': '',
    },
    'iufy3vu0': {
      'es': 'FlutterFlow',
      'ar': '',
      'de': '',
      'en': '',
    },
    '57cxhk4q': {
      'es': 'Paid on: May, 4th 2023',
      'ar': '',
      'de': '',
      'en': '',
    },
    'vxj7jq2j': {
      'es': '\$500.00',
      'ar': '',
      'de': '',
      'en': '',
    },
    '4eythey2': {
      'es': 'Paid',
      'ar': '',
      'de': '',
      'en': '',
    },
    'ot54u4pi': {
      'es': 'Notifications',
      'ar': '',
      'de': '',
      'en': '',
    },
    'g3v43dw0': {
      'es': 'Home',
      'ar': '',
      'de': '',
      'en': '',
    },
  },
  // numberemail
  {
    'dzijjnh8': {
      'es': 'Select which contact details should we use to reset your password',
      'ar': '',
      'de': '',
      'en': '',
    },
    'wobgg645': {
      'es': 'Via SMS',
      'ar': '',
      'de': '',
      'en': '',
    },
    'q25i8afv': {
      'es': '+1 111 ******99',
      'ar': '',
      'de': '',
      'en': '',
    },
    'm35ttdy9': {
      'es': 'Via Email',
      'ar': '',
      'de': '',
      'en': '',
    },
    '6wx98gxh': {
      'es': 'and***ley@yourdomain.com',
      'ar': '',
      'de': '',
      'en': '',
    },
    '1dhccaxs': {
      'es': 'Continue',
      'ar': '',
      'de': '',
      'en': '',
    },
    'apuqqqcs': {
      'es': 'Login',
      'ar': '',
      'de': '',
      'en': '',
    },
    '3mnu3wd7': {
      'es': 'Recover Password',
      'ar': '',
      'de': '',
      'en': '',
    },
    'dz9x4nfa': {
      'es': 'Home',
      'ar': '',
      'de': '',
      'en': '',
    },
  },
  // Newpassword
  {
    'jiy8vow6': {
      'es': 'Login to access your account below.',
      'ar': '',
      'de': '',
      'en': '',
    },
    '8bc2sr14': {
      'es': 'Email Address',
      'ar': '',
      'de': '',
      'en': '',
    },
    '2miqjchl': {
      'es': 'Enter your email...',
      'ar': '',
      'de': '',
      'en': '',
    },
    '7u7i28ch': {
      'es': 'Password',
      'ar': '',
      'de': '',
      'en': '',
    },
    'e8cmk16g': {
      'es': 'Enter your password...',
      'ar': '',
      'de': '',
      'en': '',
    },
    'js13sdrg': {
      'es': 'Continue',
      'ar': '',
      'de': '',
      'en': '',
    },
    'fmz8zk2n': {
      'es': 'Home',
      'ar': '',
      'de': '',
      'en': '',
    },
  },
  // GetDriver
  {
    'nwlndiq8': {
      'es': 'Sedan ',
      'ar': '',
      'de': '',
      'en': '',
    },
    'ex3d3yzy': {
      'es': 'Vol. Max 0.40m3',
      'ar': '',
      'de': '',
      'en': '',
    },
    '93sja3kr': {
      'es': 'Peso Max. 10 Kg',
      'ar': '',
      'de': '',
      'en': '',
    },
    'p7znq2fk': {
      'es': 'Take Vehicle',
      'ar': '',
      'de': '',
      'en': '',
    },
    'lt9mewem': {
      'es': 'Mini Van',
      'ar': '',
      'de': '',
      'en': '',
    },
    '5e0dz9t6': {
      'es': 'Vol. Max 1.70m3',
      'ar': '',
      'de': '',
      'en': '',
    },
    '7gm1p5u0': {
      'es': 'Peso Max. 20 Kg',
      'ar': '',
      'de': '',
      'en': '',
    },
    '09hvoil0': {
      'es': 'Take Vehicle',
      'ar': '',
      'de': '',
      'en': '',
    },
    'agqo9r86': {
      'es': 'Van',
      'ar': '',
      'de': '',
      'en': '',
    },
    'zmp6chen': {
      'es': 'Vol. Max 3.40m3',
      'ar': '',
      'de': '',
      'en': '',
    },
    'e7scdlv9': {
      'es': 'Peso Max. 60 Kg',
      'ar': '',
      'de': '',
      'en': '',
    },
    'a4bibnph': {
      'es': 'Take Vehicle',
      'ar': '',
      'de': '',
      'en': '',
    },
    '4vutv61d': {
      'es': 'Pick Up',
      'ar': '',
      'de': '',
      'en': '',
    },
    'hvwlo7yp': {
      'es': 'Vol. Max 6.00m3',
      'ar': '',
      'de': '',
      'en': '',
    },
    '0u7mq9rx': {
      'es': 'Peso Max. 90 Kg',
      'ar': '',
      'de': '',
      'en': '',
    },
    'k296mkuo': {
      'es': 'Take Vehicle',
      'ar': '',
      'de': '',
      'en': '',
    },
    '5tffweg2': {
      'es': 'Plataforma',
      'ar': '',
      'de': '',
      'en': '',
    },
    '5r5i5lmk': {
      'es': 'Vol. Max 35.00m3',
      'ar': '',
      'de': '',
      'en': '',
    },
    'chuf37qc': {
      'es': 'Peso Max. 200 Kg',
      'ar': '',
      'de': '',
      'en': '',
    },
    'pmr34pfh': {
      'es': 'Take Vehicle',
      'ar': '',
      'de': '',
      'en': '',
    },
    'pn8jwml9': {
      'es': 'Camion Cava',
      'ar': '',
      'de': '',
      'en': '',
    },
    'aydln4g9': {
      'es': 'Vol. Max 17.00m3',
      'ar': '',
      'de': '',
      'en': '',
    },
    'j4gwrwn3': {
      'es': 'Peso Max. 120 Kg',
      'ar': '',
      'de': '',
      'en': '',
    },
    'o3rtojf4': {
      'es': 'Take Vehicle',
      'ar': '',
      'de': '',
      'en': '',
    },
    'lxm893rr': {
      'es': 'Payment',
      'ar': '',
      'de': '',
      'en': '',
    },
    'vugbphil': {
      'es': 'Home',
      'ar': '',
      'de': '',
      'en': '',
    },
  },
  // Payment
  {
    'lnexvd56': {
      'es': 'My Wallet',
      'ar': '',
      'de': '',
      'en': '',
    },
    'trguqlwt': {
      'es': 'Paypal',
      'ar': '',
      'de': '',
      'en': '',
    },
    'yys38cqh': {
      'es': 'Apple Pay',
      'ar': '',
      'de': '',
      'en': '',
    },
    'k8ur1acp': {
      'es': 'Google Pay',
      'ar': '',
      'de': '',
      'en': '',
    },
    'tisdsgjt': {
      'es': '****  **** **** **** 4679',
      'ar': '',
      'de': '',
      'en': '',
    },
    '8t9to2yv': {
      'es': 'Continue',
      'ar': '',
      'de': '',
      'en': '',
    },
    'sxawdpsh': {
      'es': 'Payment',
      'ar': '',
      'de': '',
      'en': '',
    },
    'a83v9njt': {
      'es': 'Home',
      'ar': '',
      'de': '',
      'en': '',
    },
  },
  // PaymentM
  {
    'mv2wu0c0': {
      'es': 'Paypal',
      'ar': '',
      'de': '',
      'en': '',
    },
    '6uktvp25': {
      'es': 'Apple Pay',
      'ar': '',
      'de': '',
      'en': '',
    },
    'w79lyz04': {
      'es': 'Google Pay',
      'ar': '',
      'de': '',
      'en': '',
    },
    'nk8orql8': {
      'es': '****  **** **** **** 4679',
      'ar': '',
      'de': '',
      'en': '',
    },
    'u2nf9sbb': {
      'es': 'Continue',
      'ar': '',
      'de': '',
      'en': '',
    },
    'tqnacynp': {
      'es': 'Payment',
      'ar': '',
      'de': '',
      'en': '',
    },
    'u8we4bal': {
      'es': 'Home',
      'ar': '',
      'de': '',
      'en': '',
    },
  },
  // TopUp
  {
    '1qcpq1vi': {
      'es': 'Below are a summary of your invoices.',
      'ar': '',
      'de': '',
      'en': '',
    },
    'pylvyl0c': {
      'es': 'Enter the amount of top up',
      'ar': '',
      'de': '',
      'en': '',
    },
    'wg5430yy': {
      'es': '[Some hint text...]',
      'ar': '',
      'de': '',
      'en': '',
    },
    '3acuo8zv': {
      'es': '\$247',
      'ar': '',
      'de': '',
      'en': '',
    },
    'jb9bvcgq': {
      'es': '\$10',
      'ar': '',
      'de': '',
      'en': '',
    },
    'u3yzh6u1': {
      'es': '\$20',
      'ar': '',
      'de': '',
      'en': '',
    },
    'qnq5j8mx': {
      'es': '\$50',
      'ar': '',
      'de': '',
      'en': '',
    },
    'sy8pnda2': {
      'es': '\$100',
      'ar': '',
      'de': '',
      'en': '',
    },
    '4enpclpj': {
      'es': '\$200',
      'ar': '',
      'de': '',
      'en': '',
    },
    'x5jzv4nn': {
      'es': '\$250',
      'ar': '',
      'de': '',
      'en': '',
    },
    'rh5g9kti': {
      'es': '\$500',
      'ar': '',
      'de': '',
      'en': '',
    },
    'yig4hlcn': {
      'es': '\$750',
      'ar': '',
      'de': '',
      'en': '',
    },
    'jlvahqt0': {
      'es': '\$1,000',
      'ar': '',
      'de': '',
      'en': '',
    },
    'y990igoy': {
      'es': 'Continue',
      'ar': '',
      'de': '',
      'en': '',
    },
    '40hoiexc': {
      'es': 'Payment',
      'ar': '',
      'de': '',
      'en': '',
    },
    'l2xil3i2': {
      'es': 'Home',
      'ar': '',
      'de': '',
      'en': '',
    },
  },
  // MyOrder
  {
    'jnoxmvwp': {
      'es': 'Enter Track ID Number',
      'ar': '',
      'de': '',
      'en': '',
    },
    '3mwwfb10': {
      'es': 'From Me',
      'ar': '',
      'de': '',
      'en': '',
    },
    'yxh1vv0n': {
      'es': 'All',
      'ar': '',
      'de': '',
      'en': '',
    },
    'gey5vovz': {
      'es': 'Pending',
      'ar': '',
      'de': '',
      'en': '',
    },
    'n66t0xnk': {
      'es': 'On Process',
      'ar': '',
      'de': '',
      'en': '',
    },
    '1kjl6xvi': {
      'es': 'Completed',
      'ar': '',
      'de': '',
      'en': '',
    },
    '4jv1zv5z': {
      'es': 'Canceled',
      'ar': '',
      'de': '',
      'en': '',
    },
    'fdovru9w': {
      'es': 'SK92968324',
      'ar': '',
      'de': '',
      'en': '',
    },
    '1sfy3qi7': {
      'es': 'Order delivered',
      'ar': '',
      'de': '',
      'en': '',
    },
    '7nosyyqc': {
      'es': 'Completed',
      'ar': '',
      'de': '',
      'en': '',
    },
    'qfhw6v76': {
      'es': 'SK92968324',
      'ar': '',
      'de': '',
      'en': '',
    },
    'txxhmefu': {
      'es': 'On transit area',
      'ar': '',
      'de': '',
      'en': '',
    },
    'hzraxxp3': {
      'es': 'On Process',
      'ar': '',
      'de': '',
      'en': '',
    },
    'uo1w2tex': {
      'es': 'SK92968324',
      'ar': '',
      'de': '',
      'en': '',
    },
    '18qrzyzq': {
      'es': 'Waiting for driver',
      'ar': '',
      'de': '',
      'en': '',
    },
    '3wa6jj30': {
      'es': 'Pending',
      'ar': '',
      'de': '',
      'en': '',
    },
    '9i8dmlh5': {
      'es': 'SK92968324',
      'ar': '',
      'de': '',
      'en': '',
    },
    'w49z4wh3': {
      'es': 'Order canceled',
      'ar': '',
      'de': '',
      'en': '',
    },
    '5m6cfmgc': {
      'es': 'Canceled',
      'ar': '',
      'de': '',
      'en': '',
    },
    'bx2xrwg4': {
      'es': 'To Me',
      'ar': '',
      'de': '',
      'en': '',
    },
    'jlc0gmi5': {
      'es': 'All',
      'ar': '',
      'de': '',
      'en': '',
    },
    'xdv2xsjd': {
      'es': 'Pending',
      'ar': '',
      'de': '',
      'en': '',
    },
    'ggp0wpv4': {
      'es': 'On Process',
      'ar': '',
      'de': '',
      'en': '',
    },
    'kwak23h1': {
      'es': 'Completed',
      'ar': '',
      'de': '',
      'en': '',
    },
    'bjfm2rd8': {
      'es': 'Canceled',
      'ar': '',
      'de': '',
      'en': '',
    },
    'tr59ajxk': {
      'es': 'SK92968324',
      'ar': '',
      'de': '',
      'en': '',
    },
    'a6umd42d': {
      'es': 'Order delivered',
      'ar': '',
      'de': '',
      'en': '',
    },
    'c7boaa4w': {
      'es': 'Completed',
      'ar': '',
      'de': '',
      'en': '',
    },
    'b92dy1sv': {
      'es': 'SK92968324',
      'ar': '',
      'de': '',
      'en': '',
    },
    '5wg1agxu': {
      'es': 'On transit area',
      'ar': '',
      'de': '',
      'en': '',
    },
    '8dj3eq79': {
      'es': 'On Process',
      'ar': '',
      'de': '',
      'en': '',
    },
    'toeealao': {
      'es': 'SK92968324',
      'ar': '',
      'de': '',
      'en': '',
    },
    'qz50l7uo': {
      'es': 'Waiting for driver',
      'ar': '',
      'de': '',
      'en': '',
    },
    'l36wamkr': {
      'es': 'Pending',
      'ar': '',
      'de': '',
      'en': '',
    },
    'hctl0fx0': {
      'es': 'SK92968324',
      'ar': '',
      'de': '',
      'en': '',
    },
    'rtvjcfb8': {
      'es': 'Order canceled',
      'ar': '',
      'de': '',
      'en': '',
    },
    'tpjnhnzd': {
      'es': 'Canceled',
      'ar': '',
      'de': '',
      'en': '',
    },
    'gny0k2vn': {
      'es': 'Payment',
      'ar': '',
      'de': '',
      'en': '',
    },
    'g7ti9ksg': {
      'es': 'Home',
      'ar': '',
      'de': '',
      'en': '',
    },
  },
  // Maps
  {
    '5c4wzmfw': {
      'es': 'Marvin McKinney',
      'ar': '',
      'de': '',
      'en': '',
    },
    'n9ztfnxj': {
      'es': 'Home',
      'ar': '',
      'de': '',
      'en': '',
    },
  },
  // HomePage
  {
    'db3c4iwd': {
      'es': 'Welcome,',
      'ar': '',
      'de': '',
      'en': '',
    },
    'zuewrz2v': {
      'es': 'Andrew',
      'ar': '',
      'de': '',
      'en': '',
    },
    'c4gb9a6s': {
      'es': 'Your latest updates are below.',
      'ar': '',
      'de': '',
      'en': '',
    },
    '8ziyswdo': {
      'es': 'Balance',
      'ar': '',
      'de': '',
      'en': '',
    },
    'wkrpze3d': {
      'es': '\$7,630',
      'ar': '',
      'de': '',
      'en': '',
    },
    '7b01m7nr': {
      'es': 'Wallet',
      'ar': '',
      'de': '',
      'en': '',
    },
    'u3pm7gw8': {
      'es': '**** 0149',
      'ar': '',
      'de': '',
      'en': '',
    },
    'wix6wkp6': {
      'es': '05/25',
      'ar': '',
      'de': '',
      'en': '',
    },
    'm3f6f4fg': {
      'es': 'Quick Service',
      'ar': '',
      'de': '',
      'en': '',
    },
    '0wtqympm': {
      'es': 'Send Package',
      'ar': '',
      'de': '',
      'en': '',
    },
    'qzoy5txo': {
      'es': 'Agendar Viaje',
      'ar': '',
      'de': '',
      'en': '',
    },
    's06g2ss3': {
      'es': 'Transfer',
      'ar': '',
      'de': '',
      'en': '',
    },
    '2aoy0pav': {
      'es': 'Check ROutes',
      'ar': '',
      'de': '',
      'en': '',
    },
    'q3w1hn0a': {
      'es': 'Transaction',
      'ar': '',
      'de': '',
      'en': '',
    },
    'glqrmbfq': {
      'es': 'Go Far Rewards',
      'ar': '',
      'de': '',
      'en': '',
    },
    'nsvw1mm8': {
      'es': 'Income',
      'ar': '',
      'de': '',
      'en': '',
    },
    'fecogmpj': {
      'es': '\$50.00',
      'ar': '',
      'de': '',
      'en': '',
    },
    '9gebe7lw': {
      'es': 'Hello World',
      'ar': '',
      'de': '',
      'en': '',
    },
    '4f6xbxnd': {
      'es': '•',
      'ar': '',
      'de': '',
      'en': '',
    },
  },
  // MapsCopy
  {
    '55q4djkc': {
      'es': 'Continue',
      'ar': '',
      'de': '',
      'en': '',
    },
    'oesw1iqg': {
      'es': 'Home',
      'ar': '',
      'de': '',
      'en': '',
    },
  },
  // PinC
  {
    'hkstb0dr': {
      'es': 'Confirm your Code',
      'ar': '',
      'de': '',
      'en': '',
    },
    'xpe06wjp': {
      'es': 'This code helps keep your account safe and secure.',
      'ar': '',
      'de': '',
      'en': '',
    },
    '9x9t09h1': {
      'es': 'Confirm & Continue',
      'ar': '',
      'de': '',
      'en': '',
    },
    's5i6ggck': {
      'es': 'Enter Pin Code Below',
      'ar': '',
      'de': '',
      'en': '',
    },
    'cmsvoq10': {
      'es': 'Home',
      'ar': '',
      'de': '',
      'en': '',
    },
  },
  // Fingerprint
  {
    '533k1bkb': {
      'es': 'Login to access your account below.',
      'ar': '',
      'de': '',
      'en': '',
    },
    'ekqjowi8': {
      'es': 'Skip',
      'ar': '',
      'de': '',
      'en': '',
    },
    'n85p5hp6': {
      'es': 'Activate',
      'ar': '',
      'de': '',
      'en': '',
    },
    'xz60696y': {
      'es': 'Fingerprint',
      'ar': '',
      'de': '',
      'en': '',
    },
    'fchjokw6': {
      'es': 'Home',
      'ar': '',
      'de': '',
      'en': '',
    },
  },
  // Faqs
  {
    'q3p2kugr': {
      'es': 'FAQ',
      'ar': '',
      'de': '',
      'en': '',
    },
    'o1kvhgak': {
      'es': 'What is Wigo?',
      'ar': '',
      'de': '',
      'en': '',
    },
    'hed8pwxr': {
      'es': 'How to use Wigo?',
      'ar': '',
      'de': '',
      'en': '',
    },
    't8giydn4': {
      'es': 'Can I create my own shipping?',
      'ar': '',
      'de': '',
      'en': '',
    },
    '1w9qzpok': {
      'es': 'Is Wigo free to use?',
      'ar': '',
      'de': '',
      'en': '',
    },
    'am71gnpo': {
      'es': 'How to make offer on Wigo?',
      'ar': '',
      'de': '',
      'en': '',
    },
    'njgt7pqe': {
      'es': 'Contact Us',
      'ar': '',
      'de': '',
      'en': '',
    },
    'y76y368y': {
      'es': 'Customer Service',
      'ar': '',
      'de': '',
      'en': '',
    },
    'n5p1zcy9': {
      'es': 'Whatsapp',
      'ar': '',
      'de': '',
      'en': '',
    },
    '6lxtb1nu': {
      'es': 'Website',
      'ar': '',
      'de': '',
      'en': '',
    },
    '17ayzbpv': {
      'es': 'Facebook',
      'ar': '',
      'de': '',
      'en': '',
    },
    'nkje4csx': {
      'es': 'Twitter',
      'ar': '',
      'de': '',
      'en': '',
    },
    'mz0u86j3': {
      'es': 'Instagram',
      'ar': '',
      'de': '',
      'en': '',
    },
    '0n4evu4s': {
      'es': 'Help Center',
      'ar': '',
      'de': '',
      'en': '',
    },
    '0brup7ku': {
      'es': 'Home',
      'ar': '',
      'de': '',
      'en': '',
    },
  },
  // Home8ProductList
  {
    '7zxrxwey': {
      'es': 'Our menu is below',
      'ar': '',
      'de': '',
      'en': '',
    },
    'exxdtxe4': {
      'es': 'Vol. Max 0.40m3',
      'ar': '',
      'de': '',
      'en': '',
    },
    'uv0xzbco': {
      'es': 'Peso Max. 10 Kg',
      'ar': '',
      'de': '',
      'en': '',
    },
    't94clzl2': {
      'es': '\$11.00',
      'ar': '',
      'de': '',
      'en': '',
    },
    '1wrbw4ui': {
      'es': 'Title',
      'ar': '',
      'de': '',
      'en': '',
    },
    'qm8e0k4h': {
      'es': 'Subtext',
      'ar': '',
      'de': '',
      'en': '',
    },
    'y8rd0bpm': {
      'es': '\$11.00',
      'ar': '',
      'de': '',
      'en': '',
    },
    'f0ing3wl': {
      'es': 'Title',
      'ar': '',
      'de': '',
      'en': '',
    },
    'rji2xhh3': {
      'es': 'Subtext',
      'ar': '',
      'de': '',
      'en': '',
    },
    'krryujor': {
      'es': '\$11.00',
      'ar': '',
      'de': '',
      'en': '',
    },
    'pgr32fms': {
      'es': 'Notifications',
      'ar': '',
      'de': '',
      'en': '',
    },
    '9agua5ke': {
      'es': 'Home',
      'ar': '',
      'de': '',
      'en': '',
    },
  },
  // TrackPage
  {
    'khhtx1jh': {
      'es': 'Marvin McKinney',
      'ar': '',
      'de': '',
      'en': '',
    },
    'g3lc36lb': {
      'es': 'SK27367279',
      'ar': '',
      'de': '',
      'en': '',
    },
    'e0sy3iuq': {
      'es': 'Track ID',
      'ar': '',
      'de': '',
      'en': '',
    },
    'aqw78kca': {
      'es': '2 - 3 days',
      'ar': '',
      'de': '',
      'en': '',
    },
    'a2f0wk96': {
      'es': 'Estimate Time',
      'ar': '',
      'de': '',
      'en': '',
    },
    '7q8j2u67': {
      'es': '2.4 Kg',
      'ar': '',
      'de': '',
      'en': '',
    },
    'm81y5pr2': {
      'es': 'Package Weight',
      'ar': '',
      'de': '',
      'en': '',
    },
    'pe5e4qaa': {
      'es': 'Service Complete',
      'ar': '',
      'de': '',
      'en': '',
    },
    'i17f4aap': {
      'es': 'Checked in at: 4:30pm',
      'ar': '',
      'de': '',
      'en': '',
    },
    'pfqys0p7': {
      'es':
          'Your car has been complete you may now go and pay for your service at the counter.',
      'ar': '',
      'de': '',
      'en': '',
    },
    'oj559qb4': {
      'es': 'Post Service Check',
      'ar': '',
      'de': '',
      'en': '',
    },
    'oi40a5s1': {
      'es': 'Checked in at: 4:30pm',
      'ar': '',
      'de': '',
      'en': '',
    },
    'ld13nynm': {
      'es':
          'Your car is being evaluated by our tech, we are topping off your liquids and making one more quality check.',
      'ar': '',
      'de': '',
      'en': '',
    },
    '02di6p8u': {
      'es': 'In Bay -- Changing Oil',
      'ar': '',
      'de': '',
      'en': '',
    },
    '9yx4l1zl': {
      'es': 'Started at: 4:43pm',
      'ar': '',
      'de': '',
      'en': '',
    },
    '0hn4raca': {
      'es':
          'Your car is currently in the bay and our technicians are changing your oil right now.',
      'ar': '',
      'de': '',
      'en': '',
    },
    '1g7vt9ip': {
      'es': 'Preparation',
      'ar': '',
      'de': '',
      'en': '',
    },
    'gjvxv870': {
      'es': 'Completed at: 4:42pm',
      'ar': '',
      'de': '',
      'en': '',
    },
    '91aqjoex': {
      'es':
          'Our team is prepping the bay and your car in order for our techs to be able to change your oil.',
      'ar': '',
      'de': '',
      'en': '',
    },
    'cxgbxm83': {
      'es': 'Report an Issue ',
      'ar': '',
      'de': '',
      'en': '',
    },
    'u2jvuq18': {
      'es': 'Tracking',
      'ar': '',
      'de': '',
      'en': '',
    },
    'aj46b5dj': {
      'es': 'Home',
      'ar': '',
      'de': '',
      'en': '',
    },
  },
  // SizePage
  {
    'aohu8qxl': {
      'es': 'Package Category',
      'ar': '',
      'de': '',
      'en': '',
    },
    '1nsjiaeh': {
      'es': 'Document',
      'ar': '',
      'de': '',
      'en': '',
    },
    'gftd4e6a': {
      'es': 'Electronics',
      'ar': '',
      'de': '',
      'en': '',
    },
    'h2qdzmq1': {
      'es': 'Glass',
      'ar': '',
      'de': '',
      'en': '',
    },
    'kz5o9leu': {
      'es': 'Electronics',
      'ar': '',
      'de': '',
      'en': '',
    },
    'igqp4jya': {
      'es': 'Search for an item...',
      'ar': '',
      'de': '',
      'en': '',
    },
    'v7kg6xjg': {
      'es': 'Weight',
      'ar': '',
      'de': '',
      'en': '',
    },
    'yq2px4it': {
      'es': 'Option 1',
      'ar': '',
      'de': '',
      'en': '',
    },
    'je3z8aev': {
      'es': 'Kg',
      'ar': '',
      'de': '',
      'en': '',
    },
    '4qv8fahl': {
      'es': 'Search for an item...',
      'ar': '',
      'de': '',
      'en': '',
    },
    'e4yom70u': {
      'es': '0',
      'ar': '',
      'de': '',
      'en': '',
    },
    'ga2thh70': {
      'es': 'Dimension',
      'ar': '',
      'de': '',
      'en': '',
    },
    'ld3ft9ke': {
      'es': 'In',
      'ar': '',
      'de': '',
      'en': '',
    },
    '3qtmeefb': {
      'es': 'Cm',
      'ar': '',
      'de': '',
      'en': '',
    },
    '4amlam3l': {
      'es': 'Cm',
      'ar': '',
      'de': '',
      'en': '',
    },
    'hh4ksgeb': {
      'es': 'Search for an item...',
      'ar': '',
      'de': '',
      'en': '',
    },
    '1xhwdkxp': {
      'es': 'Insert Height',
      'ar': '',
      'de': '',
      'en': '',
    },
    '6t35w1gq': {
      'es': 'Option 1',
      'ar': '',
      'de': '',
      'en': '',
    },
    '7b48aa3i': {
      'es': 'Cm',
      'ar': '',
      'de': '',
      'en': '',
    },
    '8ozaw6an': {
      'es': 'Search for an item...',
      'ar': '',
      'de': '',
      'en': '',
    },
    'i3pwkq57': {
      'es': 'Insert Width',
      'ar': '',
      'de': '',
      'en': '',
    },
    'oi3jiv4t': {
      'es': 'Option 1',
      'ar': '',
      'de': '',
      'en': '',
    },
    'ny82tuj0': {
      'es': 'Cm',
      'ar': '',
      'de': '',
      'en': '',
    },
    'p7qivio5': {
      'es': 'Search for an item...',
      'ar': '',
      'de': '',
      'en': '',
    },
    'vcxhfraw': {
      'es': 'Insert Long',
      'ar': '',
      'de': '',
      'en': '',
    },
    'c1xa7lzs': {
      'es': 'Continue',
      'ar': '',
      'de': '',
      'en': '',
    },
    'oovk1tkr': {
      'es': 'Page Title',
      'ar': '',
      'de': '',
      'en': '',
    },
    '4n95gkn0': {
      'es': 'Home',
      'ar': '',
      'de': '',
      'en': '',
    },
  },
  // Preview
  {
    'jhf21ixa': {
      'es': 'Andrew Daniels',
      'ar': '',
      'de': '',
      'en': '',
    },
    'n3hztcwa': {
      'es': 'Section',
      'ar': '',
      'de': '',
      'en': '',
    },
    '8svnvdrt': {
      'es': '202 F',
      'ar': '',
      'de': '',
      'en': '',
    },
    'q9buwxfb': {
      'es': 'Seat',
      'ar': '',
      'de': '',
      'en': '',
    },
    '56us8x9k': {
      'es': '19F',
      'ar': '',
      'de': '',
      'en': '',
    },
    'l7q1urmn': {
      'es': 'Card ending in 4214',
      'ar': '',
      'de': '',
      'en': '',
    },
    'za5h6jsu': {
      'es': 'Price Breakdown',
      'ar': '',
      'de': '',
      'en': '',
    },
    '55fvptvn': {
      'es': 'Base Price',
      'ar': '',
      'de': '',
      'en': '',
    },
    '98r9ojw4': {
      'es': '\$156.00',
      'ar': '',
      'de': '',
      'en': '',
    },
    '56eodj5g': {
      'es': 'Taxes',
      'ar': '',
      'de': '',
      'en': '',
    },
    'hjs22csc': {
      'es': '\$24.20',
      'ar': '',
      'de': '',
      'en': '',
    },
    'cgyg4af4': {
      'es': 'Cleaning Fee',
      'ar': '',
      'de': '',
      'en': '',
    },
    'p7h97sp3': {
      'es': '\$40.00',
      'ar': '',
      'de': '',
      'en': '',
    },
    '6s5hi8ix': {
      'es': 'Cleaning Fee',
      'ar': '',
      'de': '',
      'en': '',
    },
    'b9y9o5us': {
      'es': '\$40.00',
      'ar': '',
      'de': '',
      'en': '',
    },
    'p629tj16': {
      'es': 'Price Breakdown',
      'ar': '',
      'de': '',
      'en': '',
    },
    '51xuxutj': {
      'es': 'Base Price',
      'ar': '',
      'de': '',
      'en': '',
    },
    'kuwlqivq': {
      'es': '\$156.00',
      'ar': '',
      'de': '',
      'en': '',
    },
    'mngagt46': {
      'es': 'Taxes',
      'ar': '',
      'de': '',
      'en': '',
    },
    'qgzsjka6': {
      'es': '\$24.20',
      'ar': '',
      'de': '',
      'en': '',
    },
    '0bk53rng': {
      'es': 'Cleaning Fee',
      'ar': '',
      'de': '',
      'en': '',
    },
    'hy70viei': {
      'es': '\$40.00',
      'ar': '',
      'de': '',
      'en': '',
    },
    '5chxm0ro': {
      'es': 'Cleaning Fee',
      'ar': '',
      'de': '',
      'en': '',
    },
    'pkdbu315': {
      'es': '\$40.00',
      'ar': '',
      'de': '',
      'en': '',
    },
    'o1wtu4iw': {
      'es': 'Price Breakdown',
      'ar': '',
      'de': '',
      'en': '',
    },
    'gjkzuyeb': {
      'es': 'Base Price',
      'ar': '',
      'de': '',
      'en': '',
    },
    'whus6to0': {
      'es': '\$156.00',
      'ar': '',
      'de': '',
      'en': '',
    },
    'zwiinkyc': {
      'es': 'Taxes',
      'ar': '',
      'de': '',
      'en': '',
    },
    '1y7weyn3': {
      'es': '\$24.20',
      'ar': '',
      'de': '',
      'en': '',
    },
    'ykcican5': {
      'es': 'Cleaning Fee',
      'ar': '',
      'de': '',
      'en': '',
    },
    'y5mpn65t': {
      'es': '\$40.00',
      'ar': '',
      'de': '',
      'en': '',
    },
    '5ikaeaop': {
      'es': 'Cleaning Fee',
      'ar': '',
      'de': '',
      'en': '',
    },
    '2b9td66s': {
      'es': '\$40.00',
      'ar': '',
      'de': '',
      'en': '',
    },
    'mxzca1nb': {
      'es': 'Home',
      'ar': '',
      'de': '',
      'en': '',
    },
  },
  // checkout
  {
    'eavd4oc0': {
      'es': 'Price Breakdown',
      'ar': '',
      'de': '',
      'en': '',
    },
    '11ev2ijx': {
      'es': 'Base Price',
      'ar': '',
      'de': '',
      'en': '',
    },
    'a3i8guug': {
      'es': '\$156.00',
      'ar': '',
      'de': '',
      'en': '',
    },
    'g0duvpm6': {
      'es': 'Taxes',
      'ar': '',
      'de': '',
      'en': '',
    },
    '54bl2jii': {
      'es': '\$24.20',
      'ar': '',
      'de': '',
      'en': '',
    },
    'iynxxogo': {
      'es': 'Cleaning Fee',
      'ar': '',
      'de': '',
      'en': '',
    },
    'qsv0f0nv': {
      'es': '\$40.00',
      'ar': '',
      'de': '',
      'en': '',
    },
    't8x2s5zo': {
      'es': 'Cleaning Fee',
      'ar': '',
      'de': '',
      'en': '',
    },
    'wbopume7': {
      'es': '\$40.00',
      'ar': '',
      'de': '',
      'en': '',
    },
    '64d9vmwy': {
      'es': 'Price Breakdown',
      'ar': '',
      'de': '',
      'en': '',
    },
    '0wzj0204': {
      'es': 'Base Price',
      'ar': '',
      'de': '',
      'en': '',
    },
    'n8tklbna': {
      'es': '\$156.00',
      'ar': '',
      'de': '',
      'en': '',
    },
    '9sbsnayz': {
      'es': 'Taxes',
      'ar': '',
      'de': '',
      'en': '',
    },
    '5olwuajh': {
      'es': '\$24.20',
      'ar': '',
      'de': '',
      'en': '',
    },
    'm6i4b68p': {
      'es': 'Cleaning Fee',
      'ar': '',
      'de': '',
      'en': '',
    },
    'p3iib6el': {
      'es': '\$40.00',
      'ar': '',
      'de': '',
      'en': '',
    },
    'kjxowxji': {
      'es': 'Cleaning Fee',
      'ar': '',
      'de': '',
      'en': '',
    },
    'jcm7ur95': {
      'es': '\$40.00',
      'ar': '',
      'de': '',
      'en': '',
    },
    'mt7t1bbc': {
      'es': 'Price Breakdown',
      'ar': '',
      'de': '',
      'en': '',
    },
    'k3bs8pbd': {
      'es': 'Base Price',
      'ar': '',
      'de': '',
      'en': '',
    },
    'glsbw73h': {
      'es': '\$156.00',
      'ar': '',
      'de': '',
      'en': '',
    },
    'n5cibgsp': {
      'es': 'Taxes',
      'ar': '',
      'de': '',
      'en': '',
    },
    'odnsi0tf': {
      'es': '\$24.20',
      'ar': '',
      'de': '',
      'en': '',
    },
    'fygcmao8': {
      'es': 'Cleaning Fee',
      'ar': '',
      'de': '',
      'en': '',
    },
    '3npnkgou': {
      'es': '\$40.00',
      'ar': '',
      'de': '',
      'en': '',
    },
    'sh084im1': {
      'es': 'Cleaning Fee',
      'ar': '',
      'de': '',
      'en': '',
    },
    'xagj31kz': {
      'es': '\$40.00',
      'ar': '',
      'de': '',
      'en': '',
    },
    'p8dd2tiw': {
      'es': 'Continue',
      'ar': '',
      'de': '',
      'en': '',
    },
    '5uoci74p': {
      'es': 'Home',
      'ar': '',
      'de': '',
      'en': '',
    },
  },
  // Directory
  {
    'w42djj21': {
      'es': 'Contacts',
      'ar': '',
      'de': '',
      'en': '',
    },
    'sqjz6vys': {
      'es': 'Add Contacts',
      'ar': '',
      'de': '',
      'en': '',
    },
    'qk6s54m8': {
      'es': 'Andrew Jackson',
      'ar': '',
      'de': '',
      'en': '',
    },
    'ht6u3utd': {
      'es': 'email@dominio.com',
      'ar': '',
      'de': '',
      'en': '',
    },
    'ee68d25e': {
      'es': 'V-123456789',
      'ar': '',
      'de': '',
      'en': '',
    },
    'bnimkcta': {
      'es': '+58 416 000 0000',
      'ar': '',
      'de': '',
      'en': '',
    },
    'sd1llee8': {
      'es': 'Mary Allen',
      'ar': '',
      'de': '',
      'en': '',
    },
    'kodmy3ms': {
      'es': 'email@dominio.com',
      'ar': '',
      'de': '',
      'en': '',
    },
    'k53wdm78': {
      'es': 'V-123456789',
      'ar': '',
      'de': '',
      'en': '',
    },
    'ci80bgwv': {
      'es': '+58 416 000 0000',
      'ar': '',
      'de': '',
      'en': '',
    },
    'mkgeblb2': {
      'es': 'Address',
      'ar': '',
      'de': '',
      'en': '',
    },
    'kv4ki7bl': {
      'es': 'Add Address',
      'ar': '',
      'de': '',
      'en': '',
    },
    '1jjuh8y5': {
      'es': 'Ress. Madre Vieja, Lecheria',
      'ar': '',
      'de': '',
      'en': '',
    },
    '4905cftr': {
      'es': 'Urbaneja. 6016',
      'ar': '',
      'de': '',
      'en': '',
    },
    'hpqr8nej': {
      'es': 'Res. Esturion, Pto. La Cruz',
      'ar': '',
      'de': '',
      'en': '',
    },
    'c71guc52': {
      'es': 'Sotillo. 6023',
      'ar': '',
      'de': '',
      'en': '',
    },
    'sfxbmc34': {
      'es': 'Home',
      'ar': '',
      'de': '',
      'en': '',
    },
  },
  // notificationsSettingsCopy
  {
    '39awdqml': {
      'es': 'Notifications',
      'ar': '',
      'de': '',
      'en': '',
    },
    '5krpbdvq': {
      'es':
          'Choose what notifcations you want to recieve below and we will update the settings.',
      'ar': '',
      'de': '',
      'en': '',
    },
    '7d9mzui3': {
      'es': 'Remember me',
      'ar': '',
      'de': '',
      'en': '',
    },
    '1qfh9q5g': {
      'es': 'Face ID',
      'ar': '',
      'de': '',
      'en': '',
    },
    'u0yszhic': {
      'es': 'Biometric ID',
      'ar': '',
      'de': '',
      'en': '',
    },
    'oesd4tu8': {
      'es': 'Google Authenticator',
      'ar': '',
      'de': '',
      'en': '',
    },
    '3pmsypdf': {
      'es': 'Change PIN',
      'ar': '',
      'de': '',
      'en': '',
    },
    'fptdh8vu': {
      'es': 'Change Password',
      'ar': '',
      'de': '',
      'en': '',
    },
    'ye6a4klr': {
      'es': 'Home',
      'ar': '',
      'de': '',
      'en': '',
    },
  },
  // Invite
  {
    '06wvdg47': {
      'es': 'Search members...',
      'ar': '',
      'de': '',
      'en': '',
    },
    'gjkusn50': {
      'es': 'Share with your frineds',
      'ar': '',
      'de': '',
      'en': '',
    },
    '2bmzakhx': {
      'es': 'UserName',
      'ar': '',
      'de': '',
      'en': '',
    },
    'y5irut3o': {
      'es': 'Remove',
      'ar': '',
      'de': '',
      'en': '',
    },
    'n7lqmhg9': {
      'es': 'UserName',
      'ar': '',
      'de': '',
      'en': '',
    },
    'a73lqkrd': {
      'es': 'Remove',
      'ar': '',
      'de': '',
      'en': '',
    },
    'ri513elx': {
      'es': 'UserName',
      'ar': '',
      'de': '',
      'en': '',
    },
    'zdd1x982': {
      'es': 'Remove',
      'ar': '',
      'de': '',
      'en': '',
    },
    'wl10g4ia': {
      'es': 'Send Invitation',
      'ar': '',
      'de': '',
      'en': '',
    },
    'l1upwlck': {
      'es': 'user@domainname.com',
      'ar': '',
      'de': '',
      'en': '',
    },
    'r70vsvfv': {
      'es': 'View',
      'ar': '',
      'de': '',
      'en': '',
    },
    'bx03xiuq': {
      'es': 'user@domainname.com',
      'ar': '',
      'de': '',
      'en': '',
    },
    'k7pcak4s': {
      'es': 'View',
      'ar': '',
      'de': '',
      'en': '',
    },
    'ccsnqtoo': {
      'es': 'Username',
      'ar': '',
      'de': '',
      'en': '',
    },
    'qq3pfjov': {
      'es': 'user@domainname.com',
      'ar': '',
      'de': '',
      'en': '',
    },
    '4coh0ejl': {
      'es': 'View',
      'ar': '',
      'de': '',
      'en': '',
    },
    'n0zyg5c8': {
      'es': 'Username',
      'ar': '',
      'de': '',
      'en': '',
    },
    'owmnss5k': {
      'es': 'user@domainname.com',
      'ar': '',
      'de': '',
      'en': '',
    },
    'kxk9390a': {
      'es': 'View',
      'ar': '',
      'de': '',
      'en': '',
    },
    'y1jcgd8k': {
      'es': 'user@domainname.com',
      'ar': '',
      'de': '',
      'en': '',
    },
    'gdnpp3pl': {
      'es': 'View',
      'ar': '',
      'de': '',
      'en': '',
    },
    '0nxdwn7u': {
      'es': 'Page Title',
      'ar': '',
      'de': '',
      'en': '',
    },
    'z1e36qja': {
      'es': 'Home',
      'ar': '',
      'de': '',
      'en': '',
    },
  },
  // bookAppointment
  {
    'sfzj3riz': {
      'es': 'Book Appointment',
      'ar': '',
      'de': '',
      'en': '',
    },
    '4skzh9os': {
      'es':
          'Fill out the information below in order to book your appointment with our office.',
      'ar': '',
      'de': '',
      'en': '',
    },
    'b87tcas2': {
      'es': 'Emails will be sent to:',
      'ar': '',
      'de': '',
      'en': '',
    },
    'iicnw3dq': {
      'es': 'Booking For',
      'ar': '',
      'de': '',
      'en': '',
    },
    '4atu73u9': {
      'es': '[Persons name]',
      'ar': '',
      'de': '',
      'en': '',
    },
    '5tkkg4yu': {
      'es': 'Type of Appointment',
      'ar': '',
      'de': '',
      'en': '',
    },
    '7w5m45zt': {
      'es': 'Doctors Visit',
      'ar': '',
      'de': '',
      'en': '',
    },
    'bmfmxg71': {
      'es': 'Routine Checkup',
      'ar': '',
      'de': '',
      'en': '',
    },
    'prt95f0g': {
      'es': 'Scan/Update',
      'ar': '',
      'de': '',
      'en': '',
    },
    'xukiv2ku': {
      'es': 'Choose Date',
      'ar': '',
      'de': '',
      'en': '',
    },
    'kpyw7qiu': {
      'es': 'Choose Date',
      'ar': '',
      'de': '',
      'en': '',
    },
    'b5umyycx': {
      'es': 'Continue',
      'ar': '',
      'de': '',
      'en': '',
    },
  },
  // bookingOld
  {
    '8laf5zmk': {
      'es': 'Book Appointment',
      'ar': '',
      'de': '',
      'en': '',
    },
    'udwhsu8p': {
      'es':
          'Fill out the information below in order to book your appointment with our office.',
      'ar': '',
      'de': '',
      'en': '',
    },
    'm6f5lawq': {
      'es': 'Email Address',
      'ar': '',
      'de': '',
      'en': '',
    },
    '8qob10s7': {
      'es': '[email]',
      'ar': '',
      'de': '',
      'en': '',
    },
    'yz52729g': {
      'es': 'Booking For',
      'ar': '',
      'de': '',
      'en': '',
    },
    '6i36vls1': {
      'es': '[Persons name]',
      'ar': '',
      'de': '',
      'en': '',
    },
    'hdmqdmzq': {
      'es': 'Type of Appointment',
      'ar': '',
      'de': '',
      'en': '',
    },
    'stpxpct6': {
      'es': 'Doctors Visit',
      'ar': '',
      'de': '',
      'en': '',
    },
    'wvgk6obb': {
      'es': 'Routine Checkup',
      'ar': '',
      'de': '',
      'en': '',
    },
    'xt7ujyt8': {
      'es': 'Scan/Update',
      'ar': '',
      'de': '',
      'en': '',
    },
    'andpn0t0': {
      'es': 'What\'s the problem?',
      'ar': '',
      'de': '',
      'en': '',
    },
    'ycaso9dc': {
      'es': 'Choose Date',
      'ar': '',
      'de': '',
      'en': '',
    },
    '2pmd2p3w': {
      'es': 'Cancel',
      'ar': '',
      'de': '',
      'en': '',
    },
    '13j05r8j': {
      'es': 'Book Now',
      'ar': '',
      'de': '',
      'en': '',
    },
  },
  // pauseCard
  {
    'dt7m486y': {
      'es': 'Pause Card',
      'ar': '',
      'de': '',
      'en': '',
    },
    '6edae99k': {
      'es': 'Are you sure you want to pause your card?',
      'ar': '',
      'de': '',
      'en': '',
    },
    'omtrfcm5': {
      'es': 'Nevermind',
      'ar': '',
      'de': '',
      'en': '',
    },
    'hw07mkb9': {
      'es': 'Yes, Pause',
      'ar': '',
      'de': '',
      'en': '',
    },
  },
  // Contact
  {
    'smbubw25': {
      'es': 'Select Contact',
      'ar': '',
      'de': '',
      'en': '',
    },
    'x35kyzfq': {
      'es': 'Andrew Jackson',
      'ar': '',
      'de': '',
      'en': '',
    },
    'fjow63rv': {
      'es': 'email@dominio.com',
      'ar': '',
      'de': '',
      'en': '',
    },
    '1z80yqwb': {
      'es': 'V-123456789',
      'ar': '',
      'de': '',
      'en': '',
    },
    '82ucb3ln': {
      'es': '+58 416 000 0000',
      'ar': '',
      'de': '',
      'en': '',
    },
    'hvh7ik55': {
      'es': 'Andrew Jackson',
      'ar': '',
      'de': '',
      'en': '',
    },
    'he9itww3': {
      'es': 'email@dominio.com',
      'ar': '',
      'de': '',
      'en': '',
    },
    'fgh3ehxw': {
      'es': 'V-123456789',
      'ar': '',
      'de': '',
      'en': '',
    },
    'ow1wqlnk': {
      'es': '+58 416 000 0000',
      'ar': '',
      'de': '',
      'en': '',
    },
    'p55bjbl5': {
      'es': 'Continue',
      'ar': '',
      'de': '',
      'en': '',
    },
  },
  // bookAppointmentCopy
  {
    '7w8gwg4z': {
      'es': 'Book Appointment',
      'ar': '',
      'de': '',
      'en': '',
    },
    'rbgbp10e': {
      'es':
          'Fill out the information below in order to book your appointment with our office.',
      'ar': '',
      'de': '',
      'en': '',
    },
    'j6i9s8zg': {
      'es': 'Emails will be sent to:',
      'ar': '',
      'de': '',
      'en': '',
    },
    'wl5s436v': {
      'es': 'Cancel',
      'ar': '',
      'de': '',
      'en': '',
    },
    'snxseflf': {
      'es': 'Book Now',
      'ar': '',
      'de': '',
      'en': '',
    },
  },
  // bookAppointmentCopy2
  {
    '67fuvet4': {
      'es': 'Book Appointment',
      'ar': '',
      'de': '',
      'en': '',
    },
    '7ctv9yg2': {
      'es':
          'Fill out the information below in order to book your appointment with our office.',
      'ar': '',
      'de': '',
      'en': '',
    },
    '7tykwqqv': {
      'es': 'Emails will be sent to:',
      'ar': '',
      'de': '',
      'en': '',
    },
    'anthulny': {
      'es': 'Booking For',
      'ar': '',
      'de': '',
      'en': '',
    },
    'nl4vorbw': {
      'es': '[Persons name]',
      'ar': '',
      'de': '',
      'en': '',
    },
    'fy7f822r': {
      'es': 'Type of Appointment',
      'ar': '',
      'de': '',
      'en': '',
    },
    '6mra8bp2': {
      'es': 'Doctors Visit',
      'ar': '',
      'de': '',
      'en': '',
    },
    'cmht0vdz': {
      'es': 'Routine Checkup',
      'ar': '',
      'de': '',
      'en': '',
    },
    'hjtj34qu': {
      'es': 'Scan/Update',
      'ar': '',
      'de': '',
      'en': '',
    },
    '6ro62jld': {
      'es': 'Choose Date',
      'ar': '',
      'de': '',
      'en': '',
    },
    'jhufhxib': {
      'es': 'Choose Date',
      'ar': '',
      'de': '',
      'en': '',
    },
    'szslbd50': {
      'es': 'Continue',
      'ar': '',
      'de': '',
      'en': '',
    },
  },
  // bookAppointmentCopy2Copy
  {
    'z22thnf3': {
      'es': 'Book Appointment',
      'ar': '',
      'de': '',
      'en': '',
    },
    'cgdt6tu9': {
      'es':
          'Fill out the information below in order to book your appointment with our office.',
      'ar': '',
      'de': '',
      'en': '',
    },
    'dtixf9i3': {
      'es': 'Emails will be sent to:',
      'ar': '',
      'de': '',
      'en': '',
    },
    '9foq6l3l': {
      'es': 'Emails will be sent to:',
      'ar': '',
      'de': '',
      'en': '',
    },
    'zii4g0vq': {
      'es': 'Booking For',
      'ar': '',
      'de': '',
      'en': '',
    },
    'odcl46wb': {
      'es': '[Persons name]',
      'ar': '',
      'de': '',
      'en': '',
    },
    'pq1uguxg': {
      'es': 'Type of Appointment',
      'ar': '',
      'de': '',
      'en': '',
    },
    'y8ypa0vm': {
      'es': 'Doctors Visit',
      'ar': '',
      'de': '',
      'en': '',
    },
    '8kg5o7gf': {
      'es': 'Routine Checkup',
      'ar': '',
      'de': '',
      'en': '',
    },
    'sfou5cvz': {
      'es': 'Scan/Update',
      'ar': '',
      'de': '',
      'en': '',
    },
    'r0636uc8': {
      'es': 'Choose Date',
      'ar': '',
      'de': '',
      'en': '',
    },
    '7k2is0ia': {
      'es': 'Choose Date',
      'ar': '',
      'de': '',
      'en': '',
    },
    'yneaks68': {
      'es': 'Continue',
      'ar': '',
      'de': '',
      'en': '',
    },
  },
  // RateTrip
  {
    'e2trx7bh': {
      'es': 'Rate Your Trip',
      'ar': '',
      'de': '',
      'en': '',
    },
    'yk04v3hd': {
      'es': 'Let us know what you thought of the place below!',
      'ar': '',
      'de': '',
      'en': '',
    },
    '58l84vgo': {
      'es': 'How would you rate it?',
      'ar': '',
      'de': '',
      'en': '',
    },
    'e4dwtjyx': {
      'es': 'Please leave a description of the place...',
      'ar': '',
      'de': '',
      'en': '',
    },
    'bohnrxhb': {
      'es': 'Submit Review',
      'ar': '',
      'de': '',
      'en': '',
    },
  },
  // Miscellaneous
  {
    'lzyb73wy': {
      'es': '',
      'ar': '',
      'de': '',
      'en': '',
    },
    'kx9cdks4': {
      'es': '',
      'ar': '',
      'de': '',
      'en': '',
    },
    'p78dprxa': {
      'es': '',
      'ar': '',
      'de': '',
      'en': '',
    },
    'm0hdzowl': {
      'es': 'please',
      'ar': '',
      'de': '',
      'en': '',
    },
    '3y5ut9x0': {
      'es': 'please',
      'ar': '',
      'de': '',
      'en': '',
    },
    '7uegzsvb': {
      'es': 'please',
      'ar': '',
      'de': '',
      'en': '',
    },
    'efvtwj7k': {
      'es': '',
      'ar': '',
      'de': '',
      'en': '',
    },
    'ec5hfa1e': {
      'es': '',
      'ar': '',
      'de': '',
      'en': '',
    },
    'q5ljwvfo': {
      'es': '',
      'ar': '',
      'de': '',
      'en': '',
    },
    'j4rmwb3h': {
      'es': '',
      'ar': '',
      'de': '',
      'en': '',
    },
    '6ah1b18f': {
      'es': '',
      'ar': '',
      'de': '',
      'en': '',
    },
    '2kos1hen': {
      'es': '',
      'ar': '',
      'de': '',
      'en': '',
    },
    'yv7yenbw': {
      'es': '',
      'ar': '',
      'de': '',
      'en': '',
    },
    'aox3s4fb': {
      'es': '',
      'ar': '',
      'de': '',
      'en': '',
    },
    'l8hv5a7z': {
      'es': '',
      'ar': '',
      'de': '',
      'en': '',
    },
    '4pjwb70a': {
      'es': '',
      'ar': '',
      'de': '',
      'en': '',
    },
    '0xlokf4y': {
      'es': '',
      'ar': '',
      'de': '',
      'en': '',
    },
    '8twlwiwt': {
      'es': '',
      'ar': '',
      'de': '',
      'en': '',
    },
    'mdprfkx0': {
      'es': '',
      'ar': '',
      'de': '',
      'en': '',
    },
    '6jsv0s76': {
      'es': '',
      'ar': '',
      'de': '',
      'en': '',
    },
    '3mq23nc7': {
      'es': '',
      'ar': '',
      'de': '',
      'en': '',
    },
    '74p3teg4': {
      'es': '',
      'ar': '',
      'de': '',
      'en': '',
    },
    'abmgnuf0': {
      'es': '',
      'ar': '',
      'de': '',
      'en': '',
    },
    '4y36w3oi': {
      'es': '',
      'ar': '',
      'de': '',
      'en': '',
    },
    't4xzlq9q': {
      'es': '',
      'ar': '',
      'de': '',
      'en': '',
    },
    '513nj4m0': {
      'es': '',
      'ar': '',
      'de': '',
      'en': '',
    },
    'a1jxfgju': {
      'es': '',
      'ar': '',
      'de': '',
      'en': '',
    },
  },
].reduce((a, b) => a..addAll(b));
